// Pantry Run — category detection (M15 two-tier)
//
// Tier 1: detectCategoryKeyword (sync, offline-safe). Returns null on miss so
// the caller can decide whether to fall through to the LLM.
// Tier 2: categorizeRemote (async, online-only). Calls the categorize_item
// Supabase Edge Function which checks household + global cache before
// hitting Gemini, and writes back to the global cache on a fresh LLM result.
//
// CATEGORY_ORDER is the single source of truth for both the picker UI and
// the section ordering on /list. The 4 new entries (Snacks, Condiments &
// Sauces, Baby, Pet) sit before 'Other' so unknown items still sort last.
//
// Keyword matching is case-insensitive, prefers the longest matching keyword,
// and only matches whole words so "creamy" doesn't sort into Dairy. Multi-
// word keywords like "peanut butter" win over single-word "peanut" thanks to
// the longest-first sort below — exploit this for disambiguation rather than
// special-casing in code.

import { createClient } from '@/lib/supabase/client'

export const CATEGORY_ORDER = [
  'Produce',
  'Dairy',
  'Meat',
  'Bakery',
  'Pantry',
  'Frozen',
  'Beverages',
  'Household',
  'Personal Care',
  'Snacks',
  'Condiments & Sauces',
  'Baby',
  'Pet',
  'Other',
] as const

export type Category = (typeof CATEGORY_ORDER)[number]

export const FALLBACK_CATEGORY: Category = 'Other'

// All categories the categorize_item function may return. Mirror of the
// Edge Function's ALL_CATEGORIES, kept in sync via the CHECK constraints
// on the DB tables.
const ALLOWED_CATEGORIES: ReadonlySet<Category> = new Set(CATEGORY_ORDER)

function isCategory(value: string): value is Category {
  return ALLOWED_CATEGORIES.has(value as Category)
}

// ────────────────────────────────────────────────────────────────────────────
// Keyword dictionary
//
// AU-first with US/UK synonyms (zucchini + courgette, capsicum + bell pepper,
// yoghurt + yogurt). Common typos included where they're frequent enough to
// matter ("tomatos", "potatos", "yougurt"). Multi-word entries for
// disambiguation ("ice cream" → Frozen, "cream cheese" → Dairy, "tomato
// sauce" → Condiments).
// ────────────────────────────────────────────────────────────────────────────

const CATEGORY_KEYWORDS: Record<Exclude<Category, 'Other'>, string[]> = {
  Produce: [
    'apple',
    'apples',
    'apricot',
    'apricots',
    'artichoke',
    'asparagus',
    'avocado',
    'avocados',
    'avo',
    'banana',
    'bananas',
    'basil',
    'bay leaves',
    'beans',
    'green beans',
    'snake beans',
    'beetroot',
    'beet',
    'berries',
    'blackberry',
    'blackberries',
    'blueberry',
    'blueberries',
    'bok choy',
    'broccoli',
    'broccolini',
    'brussels sprouts',
    'cabbage',
    'red cabbage',
    'cantaloupe',
    'capsicum',
    'capsicums',
    'bell pepper',
    'bell peppers',
    'carrot',
    'carrots',
    'cauliflower',
    'celery',
    'cherry',
    'cherries',
    'chilli',
    'chillies',
    'chili',
    'chilies',
    'choy sum',
    'coriander',
    'cilantro',
    'corn',
    'sweet corn',
    'corn cob',
    'cucumber',
    'date',
    'dates',
    'dill',
    'dragonfruit',
    'eggplant',
    'aubergine',
    'fennel',
    'fig',
    'figs',
    'garlic',
    'ginger',
    'grape',
    'grapes',
    'grapefruit',
    'green onion',
    'green onions',
    'honeydew',
    'kale',
    'kiwi',
    'kiwifruit',
    'kumara',
    'leek',
    'leeks',
    'lemon',
    'lemons',
    'lettuce',
    'iceberg lettuce',
    'cos lettuce',
    'lime',
    'limes',
    'lychee',
    'lychees',
    'mandarin',
    'mandarins',
    'mango',
    'mangoes',
    'mangos',
    'mint',
    'mushroom',
    'mushrooms',
    'button mushroom',
    'button mushrooms',
    'nectarine',
    'nectarines',
    'okra',
    'olives',
    'onion',
    'onions',
    'red onion',
    'brown onion',
    'orange',
    'oranges',
    'oregano',
    'papaya',
    'parsley',
    'parsnip',
    'parsnips',
    'passionfruit',
    'peach',
    'peaches',
    'pear',
    'pears',
    'peas',
    'snow peas',
    'sugar snap peas',
    'persimmon',
    'pineapple',
    'plum',
    'plums',
    'pomegranate',
    'potato',
    'potatoes',
    'potatos',
    'pumpkin',
    'butternut pumpkin',
    'kent pumpkin',
    'radicchio',
    'radish',
    'raspberry',
    'raspberries',
    'rhubarb',
    'rocket',
    'arugula',
    'rockmelon',
    'rosemary',
    'sage',
    'salad',
    'salad mix',
    'shallot',
    'shallots',
    'silverbeet',
    'spinach',
    'baby spinach',
    'spring onion',
    'spring onions',
    'scallion',
    'scallions',
    'strawberry',
    'strawberries',
    'swede',
    'sweet potato',
    'sweet potatoes',
    'tarragon',
    'thyme',
    'tomato',
    'tomatoes',
    'tomatos',
    'cherry tomato',
    'cherry tomatoes',
    'roma tomato',
    'roma tomatoes',
    'truss tomato',
    'truss tomatoes',
    'turmeric root',
    'turnip',
    'turnips',
    'watermelon',
    'witlof',
    'yam',
    'zucchini',
    'zucchinis',
    'courgette',
    'courgettes',
  ],

  Dairy: [
    'milk',
    'full cream milk',
    'skim milk',
    'lite milk',
    'low fat milk',
    'lactose free milk',
    'lactose-free milk',
    'a2 milk',
    'long life milk',
    'uht milk',
    'almond milk',
    'soy milk',
    'oat milk',
    'rice milk',
    'coconut milk drink',
    'milk powder',
    'condensed milk',
    'evaporated milk',
    'buttermilk',
    'cheese',
    'cheddar',
    'tasty cheese',
    'mozzarella',
    'parmesan',
    'parmigiano',
    'pecorino',
    'brie',
    'camembert',
    'feta',
    'ricotta',
    'cottage cheese',
    'cream cheese',
    'halloumi',
    'haloumi',
    'swiss cheese',
    'gouda',
    'edam',
    'blue cheese',
    'goat cheese',
    'goats cheese',
    'sliced cheese',
    'grated cheese',
    'shredded cheese',
    'string cheese',
    'butter',
    'salted butter',
    'unsalted butter',
    'cultured butter',
    'margarine',
    'spread',
    'dairy spread',
    'yoghurt',
    'yogurt',
    'yougurt',
    'greek yoghurt',
    'greek yogurt',
    'natural yoghurt',
    'natural yogurt',
    'fruit yoghurt',
    'fruit yogurt',
    'vanilla yoghurt',
    'vanilla yogurt',
    'pot set yoghurt',
    'kids yoghurt',
    'yakult',
    'cream',
    'sour cream',
    'thickened cream',
    'pure cream',
    'whipped cream',
    'double cream',
    'pouring cream',
    'custard',
    'vanilla custard',
    'eggs',
    'egg',
    'dozen eggs',
    'free range eggs',
    'cage free eggs',
    'organic eggs',
    'kefir',
    'lassi',
    'ghee',
    'quark',
    'mascarpone',
    'creme fraiche',
    'crème fraîche',
  ],

  Meat: [
    'chicken',
    'chicken breast',
    'chicken breasts',
    'chicken thigh',
    'chicken thighs',
    'chicken wing',
    'chicken wings',
    'chicken drumstick',
    'chicken drumsticks',
    'chicken mince',
    'whole chicken',
    'roast chicken',
    'chicken nibbles',
    'beef',
    'beef mince',
    'mince',
    'minced beef',
    'ground beef',
    'steak',
    'rump steak',
    'sirloin steak',
    'ribeye',
    'rib eye',
    'scotch fillet',
    't-bone',
    't bone',
    'porterhouse',
    'eye fillet',
    'beef stir fry',
    'corned beef',
    'pork',
    'pork chop',
    'pork chops',
    'pork belly',
    'pork loin',
    'pork mince',
    'pork ribs',
    'pulled pork',
    'ham',
    'leg ham',
    'shaved ham',
    'sliced ham',
    'bacon',
    'short cut bacon',
    'streaky bacon',
    'prosciutto',
    'salami',
    'pepperoni',
    'sausage',
    'sausages',
    'beef sausages',
    'pork sausages',
    'chicken sausages',
    'chorizo',
    'kransky',
    'kransky sausages',
    'bratwurst',
    'hot dog',
    'hot dogs',
    'frankfurters',
    'cheerios',
    'lamb',
    'lamb chop',
    'lamb chops',
    'lamb cutlet',
    'lamb cutlets',
    'lamb leg',
    'lamb shoulder',
    'lamb mince',
    'lamb shanks',
    'lamb backstrap',
    'veal',
    'veal mince',
    'veal schnitzel',
    'turkey',
    'turkey mince',
    'turkey breast',
    'duck',
    'duck breast',
    'goose',
    'quail',
    'kangaroo',
    'kangaroo mince',
    'venison',
    'fish',
    'salmon',
    'salmon fillet',
    'salmon fillets',
    'smoked salmon',
    'tuna',
    'tinned tuna',
    'canned tuna',
    'barramundi',
    'snapper',
    'flathead',
    'whiting',
    'cod',
    'basa',
    'mackerel',
    'sardines',
    'anchovies',
    'trout',
    'prawns',
    'shrimp',
    'cooked prawns',
    'green prawns',
    'calamari',
    'squid',
    'octopus',
    'lobster',
    'crab',
    'crab sticks',
    'scallops',
    'oysters',
    'mussels',
    'clams',
    'pipis',
    'deli meat',
    'pastrami',
    'mortadella',
    'smoked chicken',
    'smoked turkey',
    'jerky',
    'beef jerky',
    'biltong',
    'liver',
    'kidneys',
    'chicken liver',
    'rissoles',
    'schnitzel',
    'meatballs',
  ],

  Bakery: [
    'bread',
    'white bread',
    'wholemeal bread',
    'wholegrain bread',
    'multigrain',
    'multigrain bread',
    'sourdough',
    'sourdough bread',
    'rye',
    'rye bread',
    'pumpernickel',
    'baguette',
    'french stick',
    'ciabatta',
    'turkish bread',
    'turkish pide',
    'pide',
    'tortilla',
    'tortillas',
    'corn tortilla',
    'flour tortilla',
    'wrap',
    'wraps',
    'mountain bread',
    'pita',
    'pita bread',
    'pitta',
    'flatbread',
    'lavash',
    'naan',
    'naan bread',
    'roti',
    'paratha',
    'chapati',
    'roll',
    'rolls',
    'bread roll',
    'bread rolls',
    'dinner rolls',
    'hot dog bun',
    'hot dog buns',
    'hamburger bun',
    'hamburger buns',
    'burger bun',
    'burger buns',
    'brioche',
    'brioche buns',
    'croissant',
    'croissants',
    'pain au chocolat',
    'danish',
    'danish pastry',
    'donut',
    'donuts',
    'doughnut',
    'doughnuts',
    'scone',
    'scones',
    'muffin',
    'muffins',
    'english muffin',
    'english muffins',
    'crumpet',
    'crumpets',
    'bagel',
    'bagels',
    'cake',
    'birthday cake',
    'sponge cake',
    'cheesecake',
    'cupcake',
    'cupcakes',
    'lamington',
    'lamingtons',
    'tart',
    'tarts',
    'pie',
    'meat pie',
    'meat pies',
    'fruit pie',
    'pasty',
    'pasties',
    'sausage roll',
    'sausage rolls',
    'focaccia',
    'pastry',
    'pastries',
    'pretzel',
    'pretzels',
    'baguettes',
    'panini',
    'paninis',
  ],

  Pantry: [
    'rice',
    'basmati rice',
    'jasmine rice',
    'brown rice',
    'white rice',
    'arborio rice',
    'sushi rice',
    'wild rice',
    'pasta',
    'spaghetti',
    'penne',
    'fusilli',
    'macaroni',
    'linguine',
    'fettuccine',
    'ravioli',
    'tortellini',
    'lasagne sheets',
    'lasagna sheets',
    'gnocchi',
    'noodles',
    'instant noodles',
    'two minute noodles',
    'ramen',
    'udon',
    'soba',
    'rice noodles',
    'vermicelli',
    'flour',
    'plain flour',
    'self raising flour',
    'self-raising flour',
    'wholemeal flour',
    'almond flour',
    'coconut flour',
    'rice flour',
    'corn flour',
    'cornflour',
    'sugar',
    'white sugar',
    'brown sugar',
    'caster sugar',
    'icing sugar',
    'raw sugar',
    'palm sugar',
    'stevia',
    'sweetener',
    'oil',
    'olive oil',
    'extra virgin olive oil',
    'vegetable oil',
    'canola oil',
    'sunflower oil',
    'coconut oil',
    'sesame oil',
    'peanut oil',
    'rice bran oil',
    'spray oil',
    'cooking spray',
    'salt',
    'sea salt',
    'table salt',
    'rock salt',
    'pink salt',
    'himalayan salt',
    'pepper',
    'black pepper',
    'white pepper',
    'peppercorns',
    'cumin',
    'paprika',
    'smoked paprika',
    'turmeric',
    'haldi',
    'garam masala',
    'curry powder',
    'chilli powder',
    'chili powder',
    'chilli flakes',
    'cinnamon',
    'cinnamon stick',
    'nutmeg',
    'cloves',
    'cardamom',
    'star anise',
    'ginger powder',
    'mustard seeds',
    'mustard powder',
    'fenugreek',
    'methi',
    'bay leaf',
    'allspice',
    'mixed herbs',
    'italian herbs',
    'dried oregano',
    'dried basil',
    'dried thyme',
    'dried rosemary',
    'baking powder',
    'baking soda',
    'bicarb soda',
    'bicarbonate of soda',
    'yeast',
    'dried yeast',
    'instant yeast',
    'cocoa',
    'cocoa powder',
    'cacao',
    'chocolate chips',
    'choc chips',
    'cooking chocolate',
    'coffee',
    'instant coffee',
    'ground coffee',
    'coffee beans',
    'tea',
    'tea bags',
    'teabags',
    'green tea',
    'black tea',
    'english breakfast',
    'earl grey',
    'herbal tea',
    'chai',
    'chai tea',
    'tinned tomatoes',
    'canned tomatoes',
    'crushed tomatoes',
    'diced tomatoes',
    'tomato paste',
    'passata',
    'tomato puree',
    'tinned beans',
    'canned beans',
    'baked beans',
    'kidney beans',
    'black beans',
    'cannellini beans',
    'butter beans',
    'chickpeas',
    'garbanzo beans',
    'lentils',
    'red lentils',
    'green lentils',
    'brown lentils',
    'split peas',
    'quinoa',
    'couscous',
    'pearl couscous',
    'bulgur',
    'polenta',
    'semolina',
    'oats',
    'rolled oats',
    'quick oats',
    'steel cut oats',
    'porridge oats',
    'muesli',
    'granola',
    'cereal',
    'breakfast cereal',
    'weetbix',
    'weet-bix',
    'cornflakes',
    'corn flakes',
    'rice bubbles',
    'sultana bran',
    'special k',
    'nutri grain',
    'almonds',
    'cashews',
    'walnuts',
    'pistachios',
    'peanuts',
    'pecans',
    'brazil nuts',
    'hazelnuts',
    'macadamias',
    'macadamia nuts',
    'pine nuts',
    'sunflower seeds',
    'pumpkin seeds',
    'pepitas',
    'chia seeds',
    'flax seeds',
    'linseeds',
    'sesame seeds',
    'poppy seeds',
    'raisins',
    'sultanas',
    'currants',
    'dried apricots',
    'dried cranberries',
    'dried mango',
    'prunes',
    'breadcrumbs',
    'panko',
    'panko crumbs',
    'stock',
    'chicken stock',
    'beef stock',
    'vegetable stock',
    'fish stock',
    'broth',
    'bone broth',
    'stock cubes',
    'gravy powder',
    'cornstarch',
    'corn starch',
    'tapioca',
    'arrowroot',
    'gelatine',
    'gelatin',
    'vanilla',
    'vanilla essence',
    'vanilla extract',
    'vanilla bean',
    'food colouring',
    'food coloring',
    'sprinkles',
    'hundreds and thousands',
    'desiccated coconut',
    'shredded coconut',
    'coconut cream',
    'coconut milk',
  ],

  Frozen: [
    'frozen',
    'frozen peas',
    'frozen corn',
    'frozen mixed vegetables',
    'frozen veg',
    'frozen vegetables',
    'frozen broccoli',
    'frozen spinach',
    'frozen cauliflower',
    'frozen berries',
    'frozen mixed berries',
    'frozen mango',
    'frozen fruit',
    'frozen pizza',
    'frozen meal',
    'frozen meals',
    'frozen dinner',
    'frozen lasagne',
    'frozen lasagna',
    'frozen pasta',
    'frozen pies',
    'frozen pastry',
    'puff pastry',
    'filo pastry',
    'shortcrust pastry',
    'frozen dumplings',
    'dim sims',
    'spring rolls',
    'gyoza',
    'frozen burgers',
    'beef patties',
    'frozen burritos',
    'frozen wedges',
    'frozen chips',
    'frozen fries',
    'oven chips',
    'oven fries',
    'hash browns',
    'potato gems',
    'frozen fish',
    'fish fingers',
    'fish sticks',
    'fish cakes',
    'frozen prawns',
    'frozen calamari',
    'frozen chicken',
    'chicken nuggets',
    'frozen nuggets',
    'chicken kiev',
    'chicken kievs',
    'ice cream',
    'ice-cream',
    'icecream',
    'vanilla ice cream',
    'chocolate ice cream',
    'cookies and cream',
    'gelato',
    'sorbet',
    'frozen yoghurt',
    'frozen yogurt',
    'ice block',
    'ice blocks',
    'paddle pop',
    'paddle pops',
    'magnum',
    'magnums',
    'cornetto',
    'cornettos',
    'drumstick',
    'drumsticks',
    'ice cream cone',
    'ice cream cones',
    'ice cream tub',
    'ice cream sandwich',
    'ice',
    'ice cubes',
    'crushed ice',
  ],

  Beverages: [
    'juice',
    'orange juice',
    'apple juice',
    'pineapple juice',
    'cranberry juice',
    'tomato juice',
    'fruit juice',
    'mixed berry juice',
    'fresh juice',
    'soft drink',
    'soft drinks',
    'coca cola',
    'coca-cola',
    'coke',
    'diet coke',
    'coke zero',
    'pepsi',
    'pepsi max',
    'sprite',
    'fanta',
    'solo',
    'lift',
    'schweppes',
    'lemonade',
    'sparkling water',
    'mineral water',
    'soda water',
    'tonic water',
    'bottled water',
    'spring water',
    'still water',
    'water',
    'energy drink',
    'red bull',
    'monster',
    'v energy',
    'gatorade',
    'powerade',
    'sports drink',
    'iced tea',
    'ice tea',
    'iced coffee',
    'ice coffee',
    'dare',
    'ice break',
    'milkshake',
    'thickshake',
    'smoothie',
    'coconut water',
    'kombucha',
    'beer',
    'vb',
    'corona',
    'heineken',
    'peroni',
    'stella',
    'carlton',
    'crown lager',
    'craft beer',
    'ale',
    'pale ale',
    'ipa',
    'lager',
    'stout',
    'cider',
    'apple cider',
    'pear cider',
    'wine',
    'red wine',
    'white wine',
    'rose wine',
    'rosé',
    'rosé wine',
    'sparkling wine',
    'champagne',
    'prosecco',
    'sparkling',
    'cab sav',
    'shiraz',
    'merlot',
    'pinot noir',
    'sauvignon blanc',
    'chardonnay',
    'pinot grigio',
    'spirits',
    'vodka',
    'gin',
    'rum',
    'whisky',
    'whiskey',
    'scotch',
    'bourbon',
    'tequila',
    'brandy',
    'cognac',
    'liqueur',
    'baileys',
    'kahlua',
    'sake',
    'soju',
    'cocktail',
    'premix',
    'ready to drink',
    'rtd',
    'cordial',
    'flavoured milk',
    'flavored milk',
    'chocolate milk',
    'iced chocolate',
    'oak',
    'big m',
  ],

  Household: [
    'toilet paper',
    'toilet tissue',
    'toilet roll',
    'toilet rolls',
    'paper towel',
    'paper towels',
    'kitchen towel',
    'kitchen roll',
    'tissues',
    'kleenex',
    'napkins',
    'paper napkins',
    'serviettes',
    'bin bag',
    'bin bags',
    'garbage bag',
    'garbage bags',
    'rubbish bag',
    'rubbish bags',
    'trash bag',
    'trash bags',
    'bin liner',
    'bin liners',
    'compost bag',
    'compost bags',
    'dishwashing liquid',
    'dish soap',
    'dishwash liquid',
    'detergent',
    'laundry detergent',
    'laundry liquid',
    'washing powder',
    'washing liquid',
    'fabric softener',
    'bleach',
    'napisan',
    'stain remover',
    'pre wash',
    'pre-wash',
    'dishwasher tablet',
    'dishwasher tablets',
    'dishwasher powder',
    'dishwasher salt',
    'rinse aid',
    'sponge',
    'sponges',
    'scourer',
    'scourers',
    'steel wool',
    'chux',
    'cleaning cloth',
    'microfibre cloth',
    'microfiber cloth',
    'mop',
    'broom',
    'dust pan',
    'dustpan',
    'vacuum bags',
    'surface spray',
    'multi purpose spray',
    'multi-purpose spray',
    'glass cleaner',
    'windex',
    'oven cleaner',
    'toilet cleaner',
    'bathroom cleaner',
    'shower cleaner',
    'mould remover',
    'mold remover',
    'disinfectant',
    'pine o cleen',
    'dettol',
    'hand sanitiser',
    'hand sanitizer',
    'air freshener',
    'glade',
    'candle',
    'candles',
    'tea light',
    'tea lights',
    'tealights',
    'matches',
    'lighter',
    'batteries',
    'aa batteries',
    'aaa batteries',
    'd batteries',
    'c batteries',
    '9v battery',
    'light bulb',
    'light bulbs',
    'lightbulb',
    'lightbulbs',
    'led bulb',
    'foil',
    'aluminium foil',
    'aluminum foil',
    'tin foil',
    'cling film',
    'cling wrap',
    'glad wrap',
    'plastic wrap',
    'baking paper',
    'parchment paper',
    'greaseproof paper',
    'zip lock bag',
    'zip lock bags',
    'ziploc',
    'ziploc bags',
    'sandwich bag',
    'sandwich bags',
    'freezer bag',
    'freezer bags',
    'oven bags',
    'paper plates',
    'plastic cups',
    'paper cups',
    'plastic cutlery',
    'straws',
    'paper straws',
    'baking tray',
    'fly spray',
    'insect spray',
    'mortein',
    'mouse trap',
    'cockroach bait',
    'rat bait',
    'shoe polish',
    'wd40',
    'wd-40',
    'gaffer tape',
    'duct tape',
    'sticky tape',
    'blu tack',
    'blu-tack',
  ],

  'Personal Care': [
    'shampoo',
    'conditioner',
    '2 in 1 shampoo',
    'body wash',
    'soap',
    'bar soap',
    'hand soap',
    'liquid hand soap',
    'shower gel',
    'face wash',
    'cleanser',
    'face cleanser',
    'face scrub',
    'exfoliator',
    'moisturiser',
    'moisturizer',
    'face moisturiser',
    'body moisturiser',
    'sunscreen',
    'sunblock',
    'sun cream',
    'spf',
    'after sun',
    'deodorant',
    'antiperspirant',
    'roll on',
    'roll-on',
    'spray deodorant',
    'perfume',
    'cologne',
    'fragrance',
    'body spray',
    'lynx',
    'rexona',
    'toothpaste',
    'toothbrush',
    'toothbrushes',
    'electric toothbrush',
    'toothbrush heads',
    'mouthwash',
    'listerine',
    'floss',
    'dental floss',
    'razor',
    'razors',
    'disposable razors',
    'razor blades',
    'shaving cream',
    'shaving gel',
    'shaving foam',
    'aftershave',
    'after shave',
    'makeup',
    'foundation',
    'mascara',
    'lipstick',
    'lip balm',
    'chapstick',
    'lip gloss',
    'blush',
    'bronzer',
    'eyeliner',
    'eye liner',
    'eyeshadow',
    'eye shadow',
    'concealer',
    'primer',
    'setting spray',
    'makeup remover',
    'micellar water',
    'nail polish',
    'nail file',
    'nail clippers',
    'tweezers',
    'hair gel',
    'hair spray',
    'hairspray',
    'hair mousse',
    'dry shampoo',
    'hair oil',
    'hair mask',
    'hair treatment',
    'hair dye',
    'hair colour',
    'hair color',
    'hair brush',
    'hairbrush',
    'comb',
    'hair ties',
    'hair bands',
    'hairbands',
    'bobby pins',
    'cotton buds',
    'cotton tips',
    'cotton balls',
    'cotton pads',
    'cotton wool',
    'makeup wipes',
    'face wipes',
    'face cream',
    'eye cream',
    'serum',
    'face serum',
    'lotion',
    'body lotion',
    'hand cream',
    'foot cream',
    'tampon',
    'tampons',
    'pad',
    'pads',
    'sanitary pad',
    'sanitary pads',
    'panty liner',
    'panty liners',
    'menstrual cup',
    'period cup',
    'period underwear',
    'vitamins',
    'multivitamin',
    'multivitamins',
    'vitamin c',
    'vitamin d',
    'magnesium',
    'iron tablets',
    'fish oil',
    'panadol',
    'paracetamol',
    'ibuprofen',
    'nurofen',
    'aspirin',
    'panadeine',
    'cold and flu',
    'lozenges',
    'throat lozenges',
    'cough syrup',
    'bandaid',
    'band-aid',
    'bandaids',
    'plasters',
    'first aid',
    'first-aid kit',
    'antiseptic',
    'antiseptic cream',
    'betadine',
    'hand cream',
    'lip balm',
  ],

  Snacks: [
    'chips',
    'crisps',
    'potato chips',
    'corn chips',
    'tortilla chips',
    'doritos',
    'pringles',
    'smiths',
    'twisties',
    'cheezels',
    'burger rings',
    'red rock deli',
    'kettle chips',
    'thins',
    'crackers',
    'water crackers',
    'jatz',
    'ritz',
    'salada',
    'vita weat',
    'vita-weat',
    'vita-wheat',
    'cruskits',
    'savoury crackers',
    'rice crackers',
    'rice cakes',
    'corn thins',
    'shapes',
    'mini cheddars',
    'cheese ball',
    'cheese balls',
    'cheese sticks',
    'biscuits',
    'biscuit',
    'sweet biscuits',
    'cookies',
    'cookie',
    'tim tams',
    'tim tam',
    'oreos',
    'oreo',
    'arnotts',
    'scotch finger',
    'monte carlo',
    'iced vovo',
    'tiny teddy',
    'tiny teddies',
    'milk arrowroot',
    'milo bar',
    'milo bars',
    'shortbread',
    'chocolate biscuits',
    'chocolate',
    'dark chocolate',
    'milk chocolate',
    'white chocolate',
    'chocolate bar',
    'cadbury',
    'lindt',
    'kitkat',
    'kit kat',
    'mars bar',
    'snickers',
    'twix',
    'bounty',
    'freddo',
    'picnic',
    'cherry ripe',
    'turkish delight',
    'crunchie',
    'flake',
    'maltesers',
    'malteasers',
    'malteser',
    'm&ms',
    'mnms',
    'smarties',
    'lollies',
    'lolly',
    'gummies',
    'gummy bears',
    'jelly snakes',
    'snakes',
    'killer python',
    'killer pythons',
    'hard candy',
    'jelly beans',
    'sour worms',
    'sour patch',
    'sour straps',
    'fruit tingles',
    'marshmallows',
    'fairy floss',
    'popcorn',
    'popcorn kernels',
    'microwave popcorn',
    'trail mix',
    'mixed nuts',
    'roasted nuts',
    'salted nuts',
    'snack bar',
    'muesli bar',
    'muesli bars',
    'granola bar',
    'granola bars',
    'protein bar',
    'protein bars',
    'fruit bar',
    'roll-ups',
    'roll ups',
    'fruit straps',
    'fruit roll-ups',
    'dried fruit',
    'banana chips',
  ],

  'Condiments & Sauces': [
    'tomato sauce',
    'ketchup',
    'bbq sauce',
    'barbecue sauce',
    'mustard',
    'dijon mustard',
    'hot mustard',
    'wholegrain mustard',
    'american mustard',
    'mayonnaise',
    'mayo',
    'aioli',
    'garlic aioli',
    'ranch dressing',
    'salad dressing',
    'italian dressing',
    'caesar dressing',
    'balsamic glaze',
    'balsamic vinegar',
    'vinegar',
    'white vinegar',
    'apple cider vinegar',
    'rice vinegar',
    'red wine vinegar',
    'soy sauce',
    'light soy sauce',
    'dark soy sauce',
    'kecap manis',
    'fish sauce',
    'oyster sauce',
    'hoisin sauce',
    'sweet chilli sauce',
    'sweet chilli',
    'sriracha',
    'hot sauce',
    'chilli sauce',
    'tabasco',
    'worcestershire sauce',
    'worcestershire',
    'mint sauce',
    'mint jelly',
    'cranberry sauce',
    'apple sauce',
    'gravy',
    'brown sauce',
    'hp sauce',
    'pesto',
    'red pesto',
    'basil pesto',
    'salsa',
    'guacamole',
    'hummus',
    'hommus',
    'tzatziki',
    'baba ganoush',
    'relish',
    'chutney',
    'mango chutney',
    'tomato chutney',
    'pickle',
    'pickles',
    'gherkins',
    'pickled onions',
    'sauerkraut',
    'kimchi',
    'pasta sauce',
    'tomato pasta sauce',
    'alfredo sauce',
    'marinara sauce',
    'bolognese sauce',
    'napoletana',
    'arrabiata',
    'curry sauce',
    'korma sauce',
    'tikka masala',
    'tikka paste',
    'curry paste',
    'butter chicken sauce',
    'taco sauce',
    'taco seasoning',
    'salsa verde',
    'enchilada sauce',
    'jam',
    'strawberry jam',
    'raspberry jam',
    'apricot jam',
    'plum jam',
    'marmalade',
    'vegemite',
    'marmite',
    'promite',
    'nutella',
    'peanut butter',
    'almond butter',
    'cashew butter',
    'tahini',
    'honey',
    'maple syrup',
    'golden syrup',
    'treacle',
    'molasses',
    'pancake syrup',
    'lemon curd',
  ],

  Baby: [
    'nappy',
    'nappies',
    'diaper',
    'diapers',
    'huggies',
    'baby wipes',
    'wet wipes',
    'water wipes',
    'nappy rash cream',
    'nappy cream',
    'sudocrem',
    'bepanthen',
    'baby powder',
    'baby oil',
    'baby lotion',
    'baby shampoo',
    'baby wash',
    'baby bath',
    'baby formula',
    'infant formula',
    'toddler formula',
    'follow on formula',
    'follow-on formula',
    'a2 platinum',
    'aptamil',
    's26',
    'karicare',
    'bellamy',
    'baby food',
    'baby cereal',
    'rice cereal',
    'rusks',
    'baby rusks',
    'baby snack',
    'baby snacks',
    'baby biscuits',
    'teething biscuits',
    'teething rusks',
    'teething toy',
    'dummy',
    'dummies',
    'pacifier',
    'baby bottle',
    'baby bottles',
    'sippy cup',
    'bibs',
    'bib',
    'breast pads',
    'nursing pads',
    'baby sunscreen',
    'baby toothpaste',
    'baby toothbrush',
    'baby porridge',
    'baby puree',
    'baby pouches',
    'baby food pouches',
    'cot sheet',
    'cot sheets',
    'baby blanket',
    'swaddle',
    'muslin',
    'muslins',
  ],

  Pet: [
    'dog food',
    'dry dog food',
    'wet dog food',
    'puppy food',
    'dog biscuits',
    'dog treats',
    'dog chew',
    'dog chews',
    'rawhide',
    'dental chew',
    'dental chews',
    'pedigree',
    'royal canin',
    'advance',
    'optimum',
    'cat food',
    'dry cat food',
    'wet cat food',
    'kitten food',
    'cat biscuits',
    'cat treats',
    'whiskas',
    'dine',
    'fancy feast',
    'felix',
    'friskies',
    'cat litter',
    'kitty litter',
    'cat sand',
    'breeders choice',
    'fish food',
    'bird food',
    'bird seed',
    'rabbit food',
    'guinea pig food',
    'hamster food',
    'hay',
    'pet shampoo',
    'dog shampoo',
    'cat shampoo',
    'pet wipes',
    'flea treatment',
    'flea drops',
    'frontline',
    'advantage',
    'worming tablets',
    'worm tablets',
    'dog leash',
    'dog lead',
    'collar',
    'dog collar',
    'cat collar',
    'harness',
    'dog harness',
    'dog bed',
    'cat bed',
    'scratching post',
    'pet toy',
    'pet toys',
    'dog toy',
    'cat toy',
    'chew toy',
    'kong',
    'fish tank cleaner',
    'aquarium',
    'dog poo bags',
    'poo bags',
    'poop bags',
  ],
}

// Precompute (keyword, category) tuples sorted by keyword length DESC so that
// a multi-word keyword like "sweet potato" wins over "potato", and
// "peanut butter" wins over "peanut".
const SORTED_TUPLES: Array<{ keyword: string; category: Category }> = (() => {
  const tuples: Array<{ keyword: string; category: Category }> = []
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS) as Array<
    [Exclude<Category, 'Other'>, string[]]
  >) {
    for (const keyword of keywords) {
      tuples.push({ keyword: keyword.toLowerCase(), category })
    }
  }
  return tuples.sort((a, b) => b.keyword.length - a.keyword.length)
})()

/**
 * Tier 1 — fast offline keyword match. Returns null on miss so the caller
 * can decide whether to fall through to the LLM (and flag the row as
 * `category_pending`).
 */
export function detectCategoryKeyword(itemName: string): Category | null {
  const haystack = ` ${itemName.toLowerCase().trim()} `
  for (const { keyword, category } of SORTED_TUPLES) {
    if (haystack.includes(` ${keyword} `)) {
      return category
    }
  }
  return null
}

export interface RemoteCategoryResult {
  category: Category
  source: 'household' | 'global_cache' | 'llm' | 'rate_limited' | 'error'
}

/**
 * Tier 2 — calls the categorize_item Supabase Edge Function. Online-only.
 *
 * Returns a typed source so the caller can decide how to treat the result
 * (e.g. don't clear `category_pending` on 'rate_limited' or 'error' — the
 * reconnect sweep will retry next session).
 *
 * Throws only on transport / auth failure; non-OK function responses come
 * back as { category: 'Other', source: 'error' } per the Edge Function
 * contract.
 */
export async function categorizeRemote(
  name: string,
  householdId: string,
): Promise<RemoteCategoryResult> {
  const supabase = createClient()
  const { data, error } = await supabase.functions.invoke<RemoteCategoryResult>('categorize_item', {
    body: { name, household_id: householdId },
  })

  if (error || !data) {
    return { category: FALLBACK_CATEGORY, source: 'error' }
  }

  if (typeof data.category !== 'string' || !isCategory(data.category)) {
    return { category: FALLBACK_CATEGORY, source: 'error' }
  }

  return { category: data.category, source: data.source ?? 'error' }
}
