// Client-side category auto-detection. Pure, no I/O — works offline.
// Keyword matching is case-insensitive, prefers the longest matching keyword,
// and only matches whole words so "creamy" doesn't sort into Dairy.

export const CATEGORY_ORDER = [
  'Produce',
  'Dairy',
  'Meat',
  'Bakery',
  'Pantry',
  'Frozen',
  'Beverages',
  'Household',
  'Personal Care',
  'Other',
] as const

export type Category = (typeof CATEGORY_ORDER)[number]

export const FALLBACK_CATEGORY: Category = 'Other'

const CATEGORY_KEYWORDS: Record<Exclude<Category, 'Other'>, string[]> = {
  Produce: [
    'apple',
    'apples',
    'avocado',
    'avocados',
    'banana',
    'bananas',
    'basil',
    'beans',
    'beetroot',
    'berries',
    'blueberry',
    'blueberries',
    'broccoli',
    'cabbage',
    'capsicum',
    'carrot',
    'carrots',
    'cauliflower',
    'celery',
    'cherry',
    'cherries',
    'coriander',
    'corn',
    'cucumber',
    'eggplant',
    'fennel',
    'garlic',
    'ginger',
    'grape',
    'grapes',
    'kale',
    'kiwi',
    'leek',
    'lemon',
    'lemons',
    'lettuce',
    'lime',
    'limes',
    'mandarin',
    'mango',
    'mint',
    'mushroom',
    'mushrooms',
    'onion',
    'onions',
    'orange',
    'oranges',
    'parsley',
    'parsnip',
    'peach',
    'pear',
    'pears',
    'peas',
    'pepper',
    'pineapple',
    'plum',
    'potato',
    'potatoes',
    'pumpkin',
    'radish',
    'raspberry',
    'rocket',
    'rosemary',
    'salad',
    'spinach',
    'spring onion',
    'strawberry',
    'strawberries',
    'sweet potato',
    'thyme',
    'tomato',
    'tomatoes',
    'watermelon',
    'zucchini',
  ],
  Dairy: [
    'almond milk',
    'butter',
    'cheese',
    'cottage cheese',
    'cream',
    'cream cheese',
    'custard',
    'eggs',
    'feta',
    'greek yogurt',
    'haloumi',
    'margarine',
    'milk',
    'mozzarella',
    'oat milk',
    'parmesan',
    'ricotta',
    'sour cream',
    'soy milk',
    'yogurt',
    'yoghurt',
  ],
  Meat: [
    'bacon',
    'beef',
    'chicken',
    'chicken breast',
    'chorizo',
    'duck',
    'fish',
    'ham',
    'lamb',
    'mince',
    'pork',
    'prawns',
    'prosciutto',
    'salami',
    'salmon',
    'sausage',
    'sausages',
    'steak',
    'tuna',
    'turkey',
  ],
  Bakery: [
    'bagel',
    'baguette',
    'bread',
    'bread rolls',
    'brioche',
    'bun',
    'buns',
    'cake',
    'croissant',
    'donut',
    'flatbread',
    'focaccia',
    'muffin',
    'naan',
    'pita',
    'rolls',
    'sourdough',
    'tortilla',
    'tortillas',
    'wrap',
    'wraps',
  ],
  Pantry: [
    'beans',
    'cereal',
    'chickpeas',
    'chocolate',
    'cocoa',
    'coconut milk',
    'couscous',
    'crackers',
    'flour',
    'honey',
    'jam',
    'ketchup',
    'lentils',
    'mayo',
    'mayonnaise',
    'muesli',
    'mustard',
    'noodles',
    'nuts',
    'oats',
    'oil',
    'olive oil',
    'pasta',
    'peanut butter',
    'pesto',
    'porridge',
    'quinoa',
    'rice',
    'salt',
    'sauce',
    'soy sauce',
    'spice',
    'spices',
    'stock',
    'sugar',
    'tinned',
    'canned',
    'tomato sauce',
    'vinegar',
  ],
  Frozen: [
    'frozen',
    'frozen berries',
    'frozen peas',
    'frozen pizza',
    'frozen vegetables',
    'ice cream',
    'ice cubes',
    'gelato',
  ],
  Beverages: [
    'beer',
    'cider',
    'coffee',
    'cola',
    'juice',
    'kombucha',
    'lemonade',
    'orange juice',
    'soft drink',
    'sparkling water',
    'tea',
    'water',
    'wine',
  ],
  Household: [
    'aluminium foil',
    'baking paper',
    'batteries',
    'bin bags',
    'bin liners',
    'bleach',
    'candle',
    'cling wrap',
    'detergent',
    'dishwashing',
    'dishwashing liquid',
    'fabric softener',
    'glad wrap',
    'laundry powder',
    'lightbulb',
    'matches',
    'napkins',
    'paper towel',
    'paper towels',
    'sponge',
    'tissues',
    'toilet paper',
  ],
  'Personal Care': [
    'body wash',
    'conditioner',
    'cotton buds',
    'cotton pads',
    'deodorant',
    'face wash',
    'floss',
    'hand soap',
    'lip balm',
    'lotion',
    'moisturiser',
    'mouthwash',
    'pads',
    'razor',
    'shampoo',
    'shaving cream',
    'soap',
    'sunscreen',
    'tampons',
    'toothbrush',
    'toothpaste',
  ],
}

// Precompute (keyword, category) tuples sorted by keyword length DESC so that
// a multi-word keyword like "sweet potato" wins over "potato".
const SORTED_TUPLES: Array<{ keyword: string; category: Category }> = (() => {
  const tuples: Array<{ keyword: string; category: Category }> = []
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS) as Array<
    [Category, string[]]
  >) {
    for (const keyword of keywords) {
      tuples.push({ keyword: keyword.toLowerCase(), category })
    }
  }
  return tuples.sort((a, b) => b.keyword.length - a.keyword.length)
})()

export function detectCategory(itemName: string): Category {
  const haystack = ` ${itemName.toLowerCase().trim()} `
  for (const { keyword, category } of SORTED_TUPLES) {
    // Word-boundary match — surround keyword with spaces. Punctuation in the
    // item name is rare enough that we don't bother stripping it; "milk." will
    // still match because of the trailing space we appended above.
    if (haystack.includes(` ${keyword} `)) {
      return category
    }
  }
  return FALLBACK_CATEGORY
}
